sudo: required
language: php
dist: trusty

addons:
  chrome: stable

php:
  - 7.0
  - 7.1
  - 7.2

services:
  - mysql

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

script:
  - vendor/bin/phpunit

notifications:
  email: false
