language: php

php:
  - 7.2
  - 7.3

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - travis_retry yarn install

script:
  - vendor/bin/phpunit
  - yarn build

notifications:
  email: false
